/**
 * The documentation search index.
 *
 * Generated by `cargo xtask docs` from the pages themselves and committed as
 * `search.json`, exactly as the nav is. This reads that file and builds no
 * index of its own — a second indexer in a second language across a repo
 * boundary is the drift this project keeps paying for, and the gate that keeps
 * the index honest (`cargo xtask docs --check`) lives with the source.
 *
 * Headings rather than full text, which suits what this reference is asked.
 * Every mnemonic on the twenty-one generated CPU pages is a heading with its
 * description underneath, so "where is SBC" is answered directly; and the prose
 * pages' headings are the questions they answer, which full-text ranking would
 * bury under every page that happens to use the word.
 *
 * A missing file is an ordinary state, as with the nav: a release before the
 * index existed carries none, and the site renders without a search box rather
 * than failing the build.
 */
import { readFileSync } from 'node:fs';

export interface SearchEntry {
  /** The page path without `.md`: `why`, `reference/instructions/mos6502`. */
  slug: string;
  /** The page's own title. */
  page: string;
  /** The heading, absent for the page itself. */
  heading?: string;
  /** The first line of prose under it, where there is one. */
  context?: string;
}

const INDEX = '_asm198x/docs/book/search.json';

let cached: SearchEntry[] | null | undefined;

/** The generated index, or null when this build cannot see it. */
export function searchIndex(path = INDEX): SearchEntry[] | null {
  if (cached !== undefined) return cached;
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as {
      entries: SearchEntry[];
    };
    cached = parsed.entries;
  } catch {
    console.warn(
      `docs: no search index at ${path} — the documentation will render without search`,
    );
    cached = null;
  }
  return cached;
}
